name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  BUILD-DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: |
          npm install
          npm run build
          echo "cms.mino.tw" > ./dist/CNAME
          cp ./dist/index.html ./dist/404.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
